# Generated by Django 4.1.3 on 2024-01-20 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpreeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='entity_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
                ('entity_type_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.entity_type')),
            ],
        ),
        migrations.CreateModel(
            name='user_roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('email', models.CharField(default='', max_length=100, null=True)),
                ('password', models.CharField(default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
                ('entity_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.entity_data')),
                ('user_role_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.user_roles')),
            ],
        ),
    ]
