# Generated by Django 4.1.3 on 2024-01-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpreeApp', '0002_entity_data_user_roles_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
