# Generated by Django 4.1.3 on 2024-01-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpreeApp', '0004_entity_data_description_entity_type_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='active',
            field=models.BooleanField(default=0, max_length=100),
        ),
    ]
