# Generated by Django 4.1.3 on 2024-01-21 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpreeApp', '0005_user_data_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('branch_code', models.CharField(default='', max_length=100, null=True)),
                ('address', models.CharField(default='', max_length=100, null=True)),
                ('city', models.CharField(default='', max_length=100, null=True)),
                ('state', models.CharField(default='', max_length=100, null=True)),
                ('country', models.CharField(default='', max_length=100, null=True)),
                ('pincode', models.CharField(default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
                ('entity_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.entity_data')),
            ],
        ),
        migrations.AddField(
            model_name='user_data',
            name='branch_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.branch_data'),
        ),
    ]
