# Generated by Django 4.1.3 on 2024-01-21 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpreeApp', '0006_branch_data_user_data_branch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounting_group_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('nature', models.CharField(default='', max_length=100, null=True)),
                ('affect_gross_profit', models.CharField(default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
                ('branch_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.branch_data')),
                ('under_group', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accound_group', to='SpreeApp.accounting_group_data')),
            ],
        ),
    ]
