# Generated by Django 4.1.3 on 2024-01-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpreeApp', '0007_accounting_group_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='financial_year_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.CharField(default='', max_length=100, null=True)),
                ('to_date', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
                ('branch_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.branch_data')),
            ],
        ),
        migrations.CreateModel(
            name='accounting_ledger_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('opening_balance', models.CharField(default='', max_length=100, null=True)),
                ('entry_type', models.CharField(default='', max_length=100, null=True)),
                ('bill_by_bill', models.CharField(default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
                ('accounting_group_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.accounting_group_data')),
            ],
        ),
    ]
