# Generated by Django 4.1.3 on 2024-01-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpreeApp', '0008_financial_year_data_accounting_ledger_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial_year_data',
            name='active',
            field=models.BooleanField(default=0, max_length=100),
        ),
    ]
