# Generated by Django 4.1.3 on 2024-01-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpreeApp', '0009_financial_year_data_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='series_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=100, null=True)),
                ('pre_text', models.CharField(default='', max_length=100, null=True)),
                ('post_text', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
            ],
        ),
    ]
