# Generated by Django 4.1.3 on 2024-01-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpreeApp', '0011_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='location_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
            ],
        ),
    ]
