# Generated by Django 4.1.3 on 2024-01-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpreeApp', '0013_supplier_type_supplier_data_customer_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='unit_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(default='', max_length=100, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('formal_name', models.CharField(default='', max_length=100, null=True)),
                ('no_of_decimal_place', models.CharField(default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
            ],
        ),
    ]
