# Generated by Django 4.1.3 on 2024-01-22 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpreeApp', '0017_model_number_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_number_data',
            old_name='name',
            new_name='model_number',
        ),
    ]
