# Generated by Django 4.1.3 on 2024-01-22 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpreeApp', '0020_rack_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='godown_data',
            name='branch_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.branch_data'),
        ),
    ]
