# Generated by Django 4.1.3 on 2024-01-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpreeApp', '0021_godown_data_branch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rack_data',
            old_name='godwon_id',
            new_name='godown_id',
        ),
    ]
