# Generated by Django 4.1.3 on 2024-01-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpreeApp', '0022_rename_godwon_id_rack_data_godown_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_group_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
                ('under_group', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_group', to='SpreeApp.product_group_data')),
            ],
        ),
    ]
