# Generated by Django 4.1.3 on 2024-01-23 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpreeApp', '0024_pricing_level_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('product_code', models.CharField(default='', max_length=100, null=True)),
                ('purchase_rate', models.CharField(default='', max_length=100, null=True)),
                ('mrp', models.CharField(default='', max_length=100, null=True)),
                ('sales_rate', models.CharField(default='', max_length=100, null=True)),
                ('reorder_level', models.CharField(default='', max_length=100, null=True)),
                ('minimum_stock', models.CharField(default='', max_length=100, null=True)),
                ('maximum_stock', models.CharField(default='', max_length=100, null=True)),
                ('tax', models.CharField(default='', max_length=100, null=True)),
                ('bom', models.CharField(default='', max_length=100, null=True)),
                ('bar_code', models.CharField(default='', max_length=100, null=True)),
                ('active', models.BooleanField(default=0, max_length=100)),
                ('created_at', models.DateTimeField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(default='', max_length=100)),
                ('branch_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.branch_data')),
                ('brand_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.brand_data')),
                ('godown_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.godown_data')),
                ('model_number_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.model_number_data')),
                ('product_group_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.product_group_data')),
                ('rack_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.rack_data')),
                ('size_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.size_data')),
                ('unit_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpreeApp.unit_data')),
            ],
        ),
    ]
